from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

from .artifact_registry import ArtifactRegistry, load_frozen_query_overrides
from .benchmark_support import expand_env_placeholders, load_json
from .io_utils import iter_jsonl, load_json as load_json_file
from .io_utils import sha256_file, stable_hash
from .models import Candidate
from .production_midterm_adapter import checkpoint_paths_by_session

DERIVED_ARTIFACT_SCHEMA = 1


@dataclass(frozen=True)
class DerivedArtifactResult:
    path: Path
    sha256: str
    reused: bool
    embedding_calls: int
    identity: dict[str, Any]


class _Encoder:
    def encode(self, texts: Sequence[str], *, action: str) -> list[list[float]]:
        raise NotImplementedError


class _ProductionEncoder(_Encoder):
    def __init__(self, manifest_path: Path):
        from mem0.configs.base import MemoryConfig
        from mem0.utils.factory import EmbedderFactory

        manifest = load_json(manifest_path)
        config = MemoryConfig(**expand_env_placeholders(manifest.get("effective_memory_config") or {}))
        self.model = EmbedderFactory.create(
            config.embedder.provider,
            config.embedder.config,
            config.vector_store.config,
            timeout_seconds=config.embedding_timeout_seconds,
        )

    def encode(self, texts: Sequence[str], *, action: str) -> list[list[float]]:
        if not texts:
            return []
        batch = getattr(self.model, "embed_batch", None)
        if callable(batch):
            return [[float(value) for value in vector] for vector in batch(list(texts), action)]
        return [[float(value) for value in self.model.embed(text, action)] for text in texts]


class _SentenceTransformerEncoder(_Encoder):
    def __init__(
        self,
        model_id_or_path: str,
        *,
        device: str,
        revision: str | None,
        contract: Mapping[str, Any],
    ):
        from mem0.utils.factory import EmbedderFactory

        self.model = EmbedderFactory.create(
            "huggingface",
            {
                "model": model_id_or_path,
                "revision": revision,
                "model_kwargs": {"device": device},
                "encoding_contract": dict(contract),
            },
            None,
        )

    def encode(self, texts: Sequence[str], *, action: str) -> list[list[float]]:
        return [[float(value) for value in vector] for vector in self.model.embed_batch(list(texts), action)]


def _point_fingerprint(point: Mapping[str, Any]) -> str:
    return stable_hash({"id": str(point.get("id")), "payload": point.get("payload") or {}})


class DerivedArtifactBuilder:
    """Build query-only artifacts; source vectors are always generated by Production."""

    def __init__(self, registry: ArtifactRegistry):
        self.registry = registry

    @staticmethod
    def _manifest_paths(baseline: Candidate) -> list[Path]:
        paths = [Path(str(value)) for value in baseline.config.get("manifest_paths") or []]
        if not paths:
            raise ValueError("Derived artifact generation requires production MidTerm manifests")
        return paths

    def build(
        self,
        *,
        dataset_sha256: str,
        session_scope: Sequence[str],
        baseline: Candidate,
        query_representation: str = "original",
        query_artifact_path: Path | None = None,
        query_artifact_variant: str | None = None,
        embedding_model_id: str = "production",
        embedding_revision: str | None = None,
        embedding_local_path: str | None = None,
        encoding_contract: Mapping[str, Any] | None = None,
        device: str = "cpu",
    ) -> DerivedArtifactResult:
        manifests = self._manifest_paths(baseline)
        manifest_hashes = {str(path.resolve()): sha256_file(path) for path in manifests}
        query_artifact_sha = sha256_file(query_artifact_path) if query_artifact_path else None
        identity = {
            "schema": DERIVED_ARTIFACT_SCHEMA,
            "dataset_sha256": dataset_sha256,
            "session_scope": sorted(session_scope),
            "production_config": {
                "manifest_sha256": sorted(manifest_hashes.values()),
                "midterm": {
                    key: baseline.config.get(key) for key in ("top_k_sessions", "top_k_pages", "max_total_pages")
                },
            },
            "prompt_hashes": load_json(manifests[0]).get("prompt_hashes") or {},
            "model": {
                "id": embedding_model_id,
                "revision": embedding_revision,
                "encoding_contract": dict(encoding_contract or {}),
            },
            "query_representation": query_representation,
            "query_artifact_sha256": query_artifact_sha,
            "query_artifact_variant": query_artifact_variant,
        }

        def produce() -> dict[str, Any]:
            paths_by_session = checkpoint_paths_by_session(manifests)
            selected_query_texts: dict[str, str] = {}
            for session_id in session_scope:
                checkpoint_path = paths_by_session.get(session_id)
                if checkpoint_path is None:
                    raise ValueError(f"No production checkpoint manifest matched Session {session_id}")
                for checkpoint in iter_jsonl(checkpoint_path):
                    query_id = str(checkpoint.get("query_id") or "").upper()
                    if not query_id or query_id in selected_query_texts:
                        raise ValueError(f"Missing or duplicate production checkpoint: {query_id}")
                    selected_query_texts[query_id] = str(checkpoint.get("query") or "")
            if not selected_query_texts:
                raise ValueError("No production checkpoints matched the requested Session scope")
            overrides: dict[str, str] = {}
            if query_artifact_path is not None:
                overrides = load_frozen_query_overrides(
                    {
                        "query_artifact_path": str(query_artifact_path),
                        "query_artifact_variant": query_artifact_variant,
                    }
                )
            encoder: _Encoder
            if embedding_model_id == "production":
                encoder = _ProductionEncoder(manifests[0])
            else:
                if not encoding_contract:
                    raise ValueError("non-production embedding model requires a validated encoding contract")
                encoder = _SentenceTransformerEncoder(
                    embedding_local_path or embedding_model_id,
                    device=device,
                    revision=embedding_revision,
                    contract=dict(encoding_contract),
                )

            query_ids = sorted(selected_query_texts)
            query_texts = {query_id: overrides.get(query_id, selected_query_texts[query_id]) for query_id in query_ids}
            reembed_queries = embedding_model_id != "production" or query_representation != "original"
            query_vectors = (
                dict(zip(query_ids, encoder.encode([query_texts[value] for value in query_ids], action="search")))
                if reembed_queries
                else {}
            )

            embedding_calls = len(query_vectors)
            return {
                "schema": DERIVED_ARTIFACT_SCHEMA,
                "identity": identity,
                "query_texts": query_texts,
                "query_vectors": query_vectors,
                "embedding_calls": embedding_calls,
                "counts": {
                    "queries": len(query_ids),
                },
            }

        value, reused = self.registry.materialize_once(identity, produce)
        path = self.registry.artifact_path(identity)
        payload = value.get("payload") or {}
        return DerivedArtifactResult(
            path=path,
            sha256=sha256_file(path),
            reused=reused,
            embedding_calls=0 if reused else int(payload.get("embedding_calls") or 0),
            identity=identity,
        )


def load_derived_payload(path: Path) -> dict[str, Any]:
    value = load_json_file(path)
    if value.get("status") != "COMPLETE":
        raise ValueError(f"Derived artifact is incomplete: {path}")
    payload = value.get("payload")
    if not isinstance(payload, dict) or payload.get("schema") != DERIVED_ARTIFACT_SCHEMA:
        raise ValueError(f"Unsupported derived artifact: {path}")
    return payload


def point_fingerprint(point: Mapping[str, Any]) -> str:
    return _point_fingerprint(point)
