PREDEFINED_PROFILE_ATTRIBUTES = [
    {
        "attribute_key": "analysis_role",
        "attribute_name": "分析工作角色",
        "attribute_category": "user_context",
        "description": "用户明确描述或有多项强证据支持的岗位、角色或工作身份；职责描述本身不是岗位，不能据当前任务确定具体岗位。",
        "value_type": "string",
        "value_schema": {
            "type": "string",
            "enum": [
                "financial_analyst",
                "investment_analyst",
                "management_accountant",
                "fp_and_a",
                "business_controller",
                "finance_manager",
                "executive",
                "auditor",
                "other",
            ],
        },
        "merge_policy": "replace",
    },
    {
        "attribute_key": "financial_analysis_expertise_level",
        "attribute_name": "财务分析专业水平",
        "attribute_category": "user_context",
        "description": "用户在财务分析方面的知识水平；可据表达和重复行为谨慎推断，但单个复杂问题不足以认定为专家。",
        "value_type": "string",
        "value_schema": {
            "type": "string",
            "enum": ["beginner", "intermediate", "advanced", "expert"],
        },
        "merge_policy": "replace",
    },
    {
        "attribute_key": "recurring_responsibilities",
        "attribute_name": "持续工作职责",
        "attribute_category": "user_context",
        "description": "用户明确长期、周期性承担或由强工作语境支持的职责；一次性任务不能直接写入。使用抽象短语。",
        "value_type": "string_list",
        "value_schema": {
            "type": "array",
            "items": {"type": "string", "minLength": 2, "maxLength": 80},
            "maxItems": 8,
            "uniqueItems": True,
        },
        "merge_policy": "append_unique",
    },
    {
        "attribute_key": "default_report_audience",
        "attribute_name": "主要报告受众",
        "attribute_category": "user_context",
        "description": "用户通常或主要面对的报告受众；单次报告受众不足以更新，稳定工作场景或重复模式才可提取。",
        "value_type": "string",
        "value_schema": {
            "type": "string",
            "enum": [
                "finance_team",
                "business_management",
                "senior_management",
                "board",
                "investment_committee",
                "business_departments",
                "investors",
                "auditors",
                "regulators",
                "cross_functional",
                "other",
            ],
        },
        "merge_policy": "replace",
    },
    {
        "attribute_key": "response_preferences",
        "attribute_name": "回答与表达偏好",
        "attribute_category": "interaction_preference",
        "description": "用户稳定的语言、详略、结论顺序、展示形式和表达风格；带有“这次”等限定的临时格式要求不提取。",
        "value_type": "object",
        "value_schema": {
            "type": "object",
            "properties": {
                "language": {"type": ["string", "null"], "maxLength": 32},
                "detail_level": {
                    "type": ["string", "null"],
                    "enum": ["concise", "standard", "detailed", None],
                },
                "conclusion_first": {"type": ["boolean", "null"]},
                "include_tables": {"type": ["boolean", "null"]},
                "include_charts": {"type": ["boolean", "null"]},
                "prefer_actionable_output": {"type": ["boolean", "null"]},
                "skip_basic_background": {"type": ["boolean", "null"]},
                "expression_style": {
                    "type": ["string", "null"],
                    "enum": ["technical", "business", "balanced", None],
                },
            },
            "additionalProperties": False,
        },
        "merge_policy": "replace",
    },
    {
        "attribute_key": "evidence_requirements",
        "attribute_name": "证据与验证要求",
        "attribute_category": "interaction_preference",
        "description": "用户稳定要求的来源、计算、勾稽、事实与假设区分及数据缺口说明；明确纠正回答方式时可立即更新。",
        "value_type": "object",
        "value_schema": {
            "type": "object",
            "properties": {
                "evidence_level": {
                    "type": ["string", "null"],
                    "enum": ["summary", "standard", "detailed", None],
                },
                "require_source_citations": {"type": ["boolean", "null"]},
                "require_calculation_details": {"type": ["boolean", "null"]},
                "require_fact_assumption_separation": {"type": ["boolean", "null"]},
                "require_reconciliation": {"type": ["boolean", "null"]},
                "require_data_gap_disclosure": {"type": ["boolean", "null"]},
            },
            "additionalProperties": False,
        },
        "merge_policy": "replace",
    },
    {
        "attribute_key": "recommendation_preferences",
        "attribute_name": "建议呈现偏好",
        "attribute_category": "interaction_preference",
        "description": "用户对建议是否可执行、是否排序以及是否包含责任人、时间、风险影响和验证方式的稳定偏好。",
        "value_type": "object",
        "value_schema": {
            "type": "object",
            "properties": {
                "include_actionable_recommendations": {"type": ["boolean", "null"]},
                "include_priority": {"type": ["boolean", "null"]},
                "include_owner": {"type": ["boolean", "null"]},
                "include_timeline": {"type": ["boolean", "null"]},
                "include_risk_and_impact": {"type": ["boolean", "null"]},
                "include_validation_steps": {"type": ["boolean", "null"]},
            },
            "additionalProperties": False,
        },
        "merge_policy": "replace",
    },
    {
        "attribute_key": "stable_analysis_preferences",
        "attribute_name": "稳定分析习惯",
        "attribute_category": "analysis_preference",
        "description": "从强证据或重复行为归纳的抽象分析习惯；不得复制当前实体、期间、指标值、风险或决策事项。",
        "value_type": "string_list",
        "value_schema": {
            "type": "array",
            "items": {"type": "string", "minLength": 8, "maxLength": 120},
            "maxItems": 8,
            "uniqueItems": True,
        },
        "merge_policy": "append_unique",
    },
]
