PREDEFINED_PROFILE_ATTRIBUTES = [
    {
        "attribute_key": "risk_level",
        "attribute_name": "风险等级",
        "attribute_category": "risk",
        "description": "用户明确表达的投资风险承受等级",
        "value_type": "string",
        "value_schema": {
            "type": "string",
            "enum": ["conservative", "balanced", "aggressive"],
        },
        "merge_policy": "replace",
    },
    {
        "attribute_key": "max_acceptable_loss_ratio",
        "attribute_name": "最大可接受亏损比例",
        "attribute_category": "risk",
        "description": "用户可接受的最大本金亏损比例，5%保存为0.05",
        "value_type": "number",
        "value_schema": {
            "type": "number",
            "minimum": 0,
            "maximum": 1,
        },
        "merge_policy": "replace",
    },
    {
        "attribute_key": "investment_horizon",
        "attribute_name": "投资期限",
        "attribute_category": "investment",
        "description": "用户明确表达的主要投资期限",
        "value_type": "string",
        "value_schema": {
            "type": "string",
            "enum": ["short_term", "medium_term", "long_term"],
        },
        "merge_policy": "replace",
    },
    {
        "attribute_key": "liquidity_requirement",
        "attribute_name": "流动性要求",
        "attribute_category": "investment",
        "description": "用户对资金可随时支取能力的要求",
        "value_type": "string",
        "value_schema": {
            "type": "string",
            "enum": ["low", "medium", "high"],
        },
        "merge_policy": "replace",
    },
    {
        "attribute_key": "preferred_products",
        "attribute_name": "偏好产品",
        "attribute_category": "preference",
        "description": "用户明确表示偏好的金融产品",
        "value_type": "string_list",
        "value_schema": {
            "type": "array",
            "items": {"type": "string"},
            "uniqueItems": True,
        },
        "merge_policy": "append_unique",
    },
    {
        "attribute_key": "avoided_products",
        "attribute_name": "回避产品",
        "attribute_category": "preference",
        "description": "用户明确表示不愿持有或需要回避的金融产品",
        "value_type": "string_list",
        "value_schema": {
            "type": "array",
            "items": {"type": "string"},
            "uniqueItems": True,
        },
        "merge_policy": "append_unique",
    },
    {
        "attribute_key": "financial_knowledge_level",
        "attribute_name": "金融知识水平",
        "attribute_category": "knowledge",
        "description": "用户明确表达或自我评估的金融知识水平",
        "value_type": "string",
        "value_schema": {
            "type": "string",
            "enum": ["beginner", "intermediate", "advanced"],
        },
        "merge_policy": "replace",
    },
    {
        "attribute_key": "current_financial_goals",
        "attribute_name": "当前财务目标",
        "attribute_category": "goal",
        "description": "用户当前明确提出的财务目标",
        "value_type": "object_list",
        "value_schema": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "goal_type": {"type": "string"},
                    "description": {"type": "string"},
                    "target_date": {"type": ["string", "null"]},
                    "target_amount": {"type": ["number", "null"], "minimum": 0},
                    "currency": {"type": ["string", "null"]},
                    "status": {
                        "type": "string",
                        "enum": ["planned", "in_progress", "completed", "cancelled"],
                    },
                },
                "required": ["goal_type", "description"],
                "additionalProperties": False,
            },
        },
        "merge_policy": "replace",
    },
    {
        "attribute_key": "response_preferences",
        "attribute_name": "回答偏好",
        "attribute_category": "communication",
        "description": "用户明确要求的回答语言、长度、格式或表达方式",
        "value_type": "object",
        "value_schema": {
            "type": "object",
            "properties": {
                "language": {"type": ["string", "null"]},
                "detail_level": {"type": ["string", "null"]},
                "format": {"type": ["string", "null"]},
                "tone": {"type": ["string", "null"]},
            },
            "additionalProperties": False,
        },
        "merge_policy": "replace",
    },
]
